substitutions:
  _REGION: us-central1
steps:
- name: 'gcr.io/k8s-skaffold/skaffold'
  entrypoint: 'sh'
  args:
  - -xe
  - -c
  - |
    # Build and push images
    skaffold build --file-output=/workspace/artifacts.json \
                   --default-repo=us-central1-docker.pkg.dev/clouddeployment-402300/cicd-sample-repo \
                   --push=true
- name: 'google/cloud-sdk:latest'
  entrypoint: 'sh'
  args:
  - -xe
  - -c
  - |
    gcloud config set deploy/region ${_REGION}
    gcloud deploy releases create rel-${SHORT_SHA} \
                        --project=clouddeployment-402300 \
                        --region=us-central1 \
                        --delivery-pipeline=my-gke-demo-app \
                        --build-artifacts /workspace/artifacts.json 
artifacts:
  objects:
    location: 'gs://clouddeployment-402300-gceme-artifacts/'
    paths:
    - '/workspace/artifacts.json'
options:
  machineType: E2_HIGHCPU_8
timeout: 3600s



# substitutions:
#   _REGION: us-central1
# steps:
# - name: 'gcr.io/k8s-skaffold/skaffold'
#   entrypoint: 'sh'
#   args:
#   - -xe
#   - -c
#   - |
#     # Build and push images
#     skaffold build --file-output=/workspace/artifacts.json \
#                    --default-repo=us-central1-docker.pkg.dev/clouddeployment-402300/cicd-sample-repo \
#                    --push=true
# - name: 'google/cloud-sdk:latest'
#   entrypoint: 'sh'
#   args:
#   - -xe
#   - -c
#   - |
#     gcloud config set deploy/region ${_REGION}
#     gcloud deploy releases create test3-deploy \
#                         --project=clouddeployment-402300 \
#                         --region=us-central1 \
#                         --delivery-pipeline=my-gke-demo-app \
#                         --build-artifacts /workspace/artifacts.json
#   objects:
#     location: 'gs://clouddeployment-402300-gceme-artifacts/'
#     paths:
#     - '/workspace/artifacts.json'
# options:
#   machineType: E2_HIGHCPU_8
# timeout: 3600s
