apiVersion: skaffold/v2beta16
kind: Config
build:
  artifacts:
  - image: test-go
    context: ./
deploy:
 helm:
   releases:
     - name: devrelease
       chartPath: helm/dev
       valuesFiles:
         - helm/dev/values.yaml
