# Default values for Goapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


replicaCount: 1

label: goApp

image:
  name: quickstart-image
  repository: us-central1-docker.pkg.dev/clouddeployment-402300/cicd-sample-repo/quickstart-image
  # Overrides the image tag whose default is the chart appVersion.
  tag: 8ec4f06


  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

serviceName: go-app-service
service:
  type: ClusterIP
  port: 80
  containerPort: 80
